name: using custom action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: checkout code 
      uses: actions/checkcode@v4

    - name: hello world custom action
      uses: kkruze/coderco-custom@main
      with:
        who-to-greet: 'coderco team'

      