name: using custom action

on [push]

jobs:
  build:
    runs-on: ubuntu latest

    steps: 
    - name: checkout code 
      uses: actions/code@v3

    - name: hello world custom action
      uses: kkruze/coderco-custom@main
      with:
        who-to-greet: 'coderco team'

      